---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 26/04/2025 09:44
---
---
function ExcessiveWithdrawals:Commands(key, val)
	if string.find(key, "his") or string.find(key, "stat") then
		if string.find(val, "@") == nil then
			self:ShowDisabled(true)
			return true
		end
		--self:ShowUserHistory(val)
		local userObj = self:CheckData(val)
		if not userObj then return true end
		self.userWindow:Open(self.db.guildId, userObj.userName)
		return true
	end
	if string.find(key, "ign") or string.find(key, "ena") then
		if self:CheckData(val) == false then return true end
		if string.find(key, "ign") then
			self.db.guilds[self.db.guildId].users[string.lower(val)].ignore = true
		else
			self.db.guilds[self.db.guildId].users[string.lower(val)].ignore = false
		end
		local userData = self.db.guilds[self.db.guildId].users[string.lower(val)]
		local notify = "Enabled"
		if userData.ignore == true then notify = "Disabled" end
		CHAT_SYSTEM:AddMessage(self.displayName .. ' -- \nUsername: ' .. userData.userName .. '\nNotifications: ' .. notify)
		return true
	end
	if string.find(key, "remov") then
		if self:CheckData(val) == false then return true end
		local userData = self.db.guilds[self.db.guildId].users[string.lower(val)]
		local userName = userData.userName
		self.db.guilds[self.db.guildId].users[string.lower(val)] = nil
		CHAT_SYSTEM:AddMessage(self.displayName .. ' -- \nGuild bank history for ' .. userData.userName .. ' has been removed/reset.')
		return true
	end
	if string.find(key, "reset") then
		if string.find(val, "hist") then
			self.db.guilds = {}
			CHAT_SYSTEM:AddMessage(self.displayName .. ' -- \n Successfully reset all guild bank history.')
		else
			local guildName = nil
			if tonumber(val) ~= nil then guildName = GetGuildName(val) end
			if self.db.guilds ~= nil then
				if guildName == nil or guildName == "" then
					CHAT_SYSTEM:AddMessage(self.displayName .. " -- \n |cFF0000ERROR: Guild number doesn't exist.")
					return true
				elseif self.db.guilds[val] == nil then
					CHAT_SYSTEM:AddMessage(self.displayName .. ' -- \n |cFF0000ERROR: No data was found for ' .. guildName .. '.')
					return true
				end
				self:ResetGuild(val)
			end
			CHAT_SYSTEM:AddMessage(self.displayName .. ' -- \n Successfully reset guild bank history for ' .. guildName .. '.')
		end
		return true
	end
	if string.find(key, "list") then
		local results = self:AnalyzeUsers(self.db.guildId)
		self:ListAnalysis(results)
		return true
	end
	return false
end

function ExcessiveWithdrawals.Cmd(txt)
	if txt == "" then
		ExcessiveWithdrawals.window:Open()
		--CHAT_SYSTEM:AddMessage(ExcessiveWithdrawals.displayName .. ': type "/exwithdraw" for a list of commands.')
		return
	end
	if txt:sub(1, 1) == "@" then
		txt = "history "..txt
	end
	local arr = {}
	local i = 1
	for val in string.gmatch(txt,"%w+") do
		arr[i] = val
		i = i + 1
	end
	if string.find(txt, "@") then arr[2] = "@" .. arr[2] end
	if ExcessiveWithdrawals:Commands(arr[1], arr[2]) == true then return end
	CHAT_SYSTEM:AddMessage(ExcessiveWithdrawals.displayName .. ' -- \n |cFF0000ERROR: Chat command was not found.|r \nFor a list of commands, type: /exwithdraw')
end

