---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 14/05/2025 22:13
---

local function getSummary(self, userName)
	if userName:sub(1, 1) ~= "@" then userName = "@" .. userName end
	local userData = self.db.guilds[self.db.guildId].users[string.lower(userName)]
	local out = 'Items Deposited: ' .. self:CommaValue(userData.itemsDeposit)  .. '   value: ' .. self:CommaValue(userData.itemsDepositVal) .. ' gold\n' ..
					    'Items Withdrawn: ' .. self:CommaValue(userData.itemsWithdraw) .. '   value: ' .. self:CommaValue(userData.itemsWithdrawVal) .. ' gold\n' ..
					    'Cash Donated: ' .. self:CommaValue(userData.goldDeposit) .. ' gold\n'
	if userData.goldWithdraw > 0 then
		out = out .. 'Cash Withdrawn: ' .. self:CommaValue(userData.goldWithdraw) .. ' gold\n'
	end --' |  First Scanned on ' .. GetDateStringFromTimestamp(userData.initialScan) .. "\n"
	local itemTot = userData.itemsDepositVal - userData.itemsWithdrawVal
	local goldTot = userData.goldDeposit - userData.goldWithdraw
	local grandTot = itemTot + goldTot
	out = out .. "Current Balance: " .. self:CommaValue(grandTot) .. " gold"
	return out
end

local function substitutePlaceholders(self, text)
	text = string.gsub(text, "\$GUILD", GetGuildName(self.db.guildId))
	text = string.gsub(text, "\$USER", self.userWindow.userName)
	text = string.gsub(text, "\$SUMMARY", getSummary(self, self.userWindow.userName))
	return text
end

function ExcessiveWithdrawals:CreateMail(to, subject, body)
	subject = substitutePlaceholders(self, subject)
	body = substitutePlaceholders(self, body)

	SCENE_MANAGER:Show('mailSend')
	zo_callLater(function()
		ZO_MailSendToField:SetText(to)
		ZO_MailSendSubjectField:SetText(subject)
		ZO_MailSendBodyField:SetText(body)
		--QueueMoneyAttachment(amount)
		ZO_MailSendBodyField:TakeFocus()
	end, 200)
end
