---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 22/04/2025 19:14
---


function ExcessiveWithdrawals:Menu()
	local LAM2 = LibStub:GetLibrary("LibAddonMenu-2.0")

	local panelData = {
		type = "panel",
		name = self.addonName,
		displayName = self.displayName,
		author = "depeshmood",
		version = "18.23.0",
		slashCommand = "/exwithdraw",
		registerForRefresh = true,
		registerForDefaults = true,
	}
	LAM2:RegisterAddonPanel(self.name .. "LAM2Options", panelData)
	local optionsTable = {
		{
			type = "header",
			name = "Guild Information",
			width = "full",
		},
		{
			type = "dropdown",
			name = "Guild",
			tooltip = "This is the guild that you would like to use to scan.",
			choices = self:GetGuilds(),
			default = "-",
			getFunc = function() return self.db.guild end,
			setFunc = function(choice) self.db.guild = choice end
		},
		{
			type = "dropdown",
			name = "Exclude Guild Rank(s)     #",
			tooltip = "The guild rank(s) to exclude, in the order they appear in the guild pane, and above.\n1 = Guild Master",
			choices = {"-", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
			default = "-",
			getFunc = function() return self.db.guildRank end,
			setFunc = function(choice) self.db.guildRank = choice end
		},
		{
			type = "editbox",
			name = "Ignore up to                       $",
			tooltip = "Once the amount withdrawn exceeds this amount, you will begin to receive notifications per username.",
			width = "full",
			default = self.defaults.ignoreAmt,
			getFunc = function() return self.db.ignoreAmt end,
			setFunc = function(choice) self.db.ignoreAmt = choice end,
		},
		{
			type = "button",
			name = "Monitor Guild",
			tooltip = "This will start the addon for monitoring the guild bank's history, but only needs to be used after configuring the information above or to see any warnings.",
			width = "half",
			func = function() self:MonitorGuild() end
		},
		{
			type = "button",
			name = "List Disabled",
			tooltip = "This will list all usernames and guild bank total value, for gold/items deposited and withdrawn, that have their notifications disabled.",
			width = "half",
			func = function() self:ShowDisabled(false) end
		},
		{
			type = "header",
			name = "Automated Demotions (optional)",
			width = "full",
		},
		{
			type = "editbox",
			name = "Ignore up to                       $",
			tooltip = "Once the amount withdrawn exceeds this amount the user will automatically be demoted, while excluding the guild rank(s) specified above.",
			width = "full",
			default = 5000,
			getFunc = function() return self.db.demoteAmt end,
			setFunc = function(choice) self.db.demoteAmt = choice end,
		},
		{
			type = "dropdown",
			name = "New Guild Rank               #",
			tooltip = "The guild rank that you would like to demote players to that exceed the above amount. This should be a rank that does not have guild bank withdrawal permissions.",
			choices = {"-", 3, 4, 5, 6, 7, 8, 9, 10},
			default = 10,
			getFunc = function() return self.db.demoteRank end,
			setFunc = function(choice) self.db.demoteRank = choice end
		},
		{
			type = "header",
			name = "Member Management",
			width = "full",
		},
		{
			type = "editbox",
			name = "Username, including \"@\"",
			tooltip = "This is the guild member's username that you would like to manage.",
			width = "full",
			default = self.defaults.gUser,
			getFunc = function() return self.db.gUser end,
			setFunc = function(choice) self.db.gUser = choice end,
		},
		{
			type = "button",
			name = "Disable",
			tooltip = "This will disable all notifications for this user, until they do another guild bank transaction.",
			width = "half",
			func = function() self:Commands("ignore", self.db.gUser) end
		},
		{
			type = "button",
			name = "History",
			tooltip = "View the guild member's guild bank history.",
			width = "half",
			func = function() self:Commands("history", self.db.gUser) end
		},
		{
			type = "button",
			name = "Remove",
			tooltip = "This will remove the above username from the database for " .. self.displayName .. ", until they make new guild bank transactions.",
			width = "half",
			func = function() self:Commands("remove", self.db.gUser) end
		},
		{
			type = "button",
			name = "Enable",
			tooltip = "This will enable all chat window notifications for this user.",
			width = "half",
			func = function() self:Commands("enable", self.db.gUser) end
		},
		{
			type = "header",
			name = "Addon Settings",
			width = "full",
		},
		{
			type = "slider",
			name = "Scan Every ... minute(s)",
			tooltip = "This allows you to change the duration of time between each scan and notification(s).",
			width = "full",
			min = 1,
			max = 60,
			default = 10,
			getFunc = function() return self.db.delay end,
			setFunc = function(value)
				self.db.delay = value
				if tonumber(value) ~= nil then
					EVENT_MANAGER:UnregisterForUpdate(self.name)
					EVENT_MANAGER:RegisterForUpdate(self.name, tonumber(value) * 60000, function() ExcessiveWithdrawals:MonitorGuild() end)
				end
			end
		},
		{
			type = "checkbox",
			name = "Disable Warnings",
			tooltip = "This will disable the warning and/or error messages when pricing addons, Master Merchant and Tamriel Trade Centre, are not found and/or enabled.",
			width = "full",
			getFunc = function() return self.db.warnings end,
			setFunc = function(value) self.db.warnings = value end
		},
		{
			type = "button",
			name = "Reset All",
			tooltip = "This will reset and clear any and/or all guild data currently stored in " .. self.displayName .. ". (see warning below)",
			width = "half",
			func = function() self:Commands("reset", "history") end
		},
		{
			type = "button",
			name = "Reset Guild",
			tooltip = "This will clear all data for the currently selected guild. (see warning below)",
			width = "half",
			func = function() self:Commands("reset", self:GetGuild(self.db.guild)) end
		},
		{
			type = "header",
			name = "Chat Commands",
			width = "full",
		},
		{
			type = "description",
			text = "To open this menu, type: /exwithdraw\n\nUser's History: /excessive history @USERNAME\nDisable notifications: /excessive ignore @USERNAME\n               (auto-enabled upon deposit/withdrawal)\nEnable notifications: /excessive enable @USERNAME\nRemove history: /excessive remove @USERNAME\n\nList users with disabled notifications: /excessive history all\n               (configured guild members only)\n\nReset guild history: /excessive reset GUILD_NUMBER\nReset all history: /excessive reset history\n               (see below, as this can have a serious impact)\n\nPlease note: The guild bank's history is limited to 10 days, including today, and is only able to obtain information 9 days into the past. You will need to allow this addon to load and populate regularly within that timeframe in order to keep the information up-to-date.\n\nSlash commands can sometimes cause the UI to become unresponsive.\nType \"/reloadui\" to reset your user interface and resolve the issue."
		}
	}
	LAM2:RegisterOptionControls(self.name .. "LAM2Options", optionsTable)
end
