---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by david.
--- DateTime: 30/04/2025 13:10
---
local Window = ExcessiveWithdrawals.window

function Window:Init()
	self.userListCtrl = self:GetNamedChild("UserList")

	ZO_ScrollList_AddDataType(self.userListCtrl, 0, "EWWindow_UserRow", 35, function(...) self:layoutUserRow(...) end, nil, nil, nil)
end

local function fmtnum(val)
	return zo_strformat("<<1>>", ZO_LocalizeDecimalNumber(math.floor(val)))
end

function Window:Open()
	self:SetHidden(false)

	ZO_ScrollList_Clear(self.userListCtrl)
	local scrollData = ZO_ScrollList_GetDataList(self.userListCtrl)

	local results = ExcessiveWithdrawals:AnalyzeUsers(ExcessiveWithdrawals.db.guildId)

	for i = 1, #results do
		local entry = ZO_ScrollList_CreateDataEntry(0, results[i])
		table.insert(scrollData, entry)
	end


	ZO_ScrollList_Commit(self.userListCtrl)

end

function Window:layoutUserRow(rowCtrl, data, _)
	rowCtrl.nameLabel:SetText(data.userName or "-")
	rowCtrl.addedLabel:SetText(fmtnum(data.itemsDepositVal) or "-")
	rowCtrl.removedLabel:SetText(fmtnum(data.itemsWithdrawVal) or "-")
	local cashDonated = data.goldDeposit - data.goldWithdraw
	rowCtrl.donatedLabel:SetText(fmtnum(cashDonated) or "-")
	rowCtrl.balanceLabel:SetText(("-"..fmtnum(-data.balance)) or "-")

	local colour = data.member and ZO_DEFAULT_ENABLED_COLOR or ZO_DEFAULT_DISABLED_COLOR

	rowCtrl.nameLabel:SetColor(colour:UnpackRGBA())
	rowCtrl.addedLabel:SetColor(colour:UnpackRGBA())
	rowCtrl.removedLabel:SetColor(colour:UnpackRGBA())
	rowCtrl.donatedLabel:SetColor(colour:UnpackRGBA())
	rowCtrl.balanceLabel:SetColor(colour:UnpackRGBA())
end
